apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-rag
  # namespace: llm-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llm
  template:
    metadata:
      labels:
        app: llm
    spec:
      containers:
      - name: llm
        image: dhquanganh/llm-service:latest
        ports:
        - containerPort: 5002
        envFrom:
        - secretRef:  # This is the correct format
            name: llm-secrets
        env:
          - name: FAISS_SERVICE_URL
            value: "http://192.168.16.95:5001/query"
---
apiVersion: v1
kind: Service
metadata:
  name: llm-service
  # namespace: llm-service
spec:
  selector:
    app: llm
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002
  type: LoadBalancer