apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-rag
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llm
  template:
    metadata:
      labels:
        app: llm
    spec:
      containers:
      - name: llm
        image: dhquanganh/llm-rag-service:latest
        ports:
        - containerPort: 5002
        envFrom:
        - name: FAISS_SERVICE_URL
          value: "http://faiss-service:5001/query"
        - secretRef:
            name: llm-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: llm-rag-service
spec:
  selector:
    app: llm
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002
  type: NodePort