apiVersion: apps/v1
kind: Deployment
metadata:
  name: knowledge-base
  # namespace: faiss-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: faiss
  template:
    metadata:
      labels:
        app: faiss
    spec:
      containers:
      - name: faiss
        image: dhquanganh/faiss-service:latest
        ports:
        - containerPort: 5001
        envFrom:
        - secretRef:
            name: llm-secrets
