apiVersion: apps/v1
kind: Deployment
metadata:
  name: faiss-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: faiss
  template:
    metadata:
      labels:
        app: faiss
    spec:
      containers:
      - name: faiss
        image: dhquanganh/faiss-service:latest
        ports:
        - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: faiss-service
spec:
  selector:
    app: faiss
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001